( THIS EXAMPLE IS FOR LOOPING OVER A RANGE )
( WHILE CLEARING VARIABLES ALONG THE WAY )

( SET THE START OF THE VARIABLE RANGE TO CLEAR )
#1 = 100

( '147' IS THE END OF THE RANGE TO CLEAR ) 
WHILE[ #1 LE 147] DO1

( CLEAR THE REGISTER REFERENCED BY #1 CURRENT VALUE)
#[#1]=#0

( INCREMENT OUR REGISTER TARGET )
#1 = #1 + 1

( THIS MARKS THE END OF THE WHILE LOOP )
( NOTE THE TRAILING NUMBER ON `END#` )
( THIS MUST MATCH THE `DO#` TO WORK )
END1 

( MULTIPLE WHILE LOOPS CAN RESIDE IN A PROGRAM )
( AS WELL AS NESTED LOOPS, AND AS LONG AS )
( YOU KEEP TRACK OF THE DO/END # PAIRS IT WILL WORK )